Added russian translate file ru.po
flozz/yoga-image-optimizer pull request #21
Opened 2022-06-09 16:42 UTC by catdesign-group

Hello. Please check my translation file and do the merge

2022-06-11 18:24 UTC, flozz requested changes
Thank you for helping translating YOGA! :)

It seems there is few mistakes, can you check and fix them to allow me to merge you PR? :)

NOTE: There is also some missing translations but that's not really a problem as untranslated strings will be displayed in english.

2022-06-11 18:24 UTC, flozz commented on locales/ru.po
> +"Un'interfaccia grafica per convertire e ottimizzare immagini JPEG, PNG e "
This does not look like Russian :)

2022-06-11 18:24 UTC, flozz commented on locales/ru.po
> +msgstr "Разрешение"
Not sure for this one according to Google Translate that seems to translate it by « Максимальный размер »(but I do not speak Russian)

2022-06-11 18:24 UTC, flozz commented on locales/ru.po
> +msgstr "Оптимизировать PNG"
I am not really sure for this one (but I do not speak Russian). It must insists on the fact that it is slow :)

2022-06-11 18:24 UTC, flozz commented on locales/ru.po
> +msgstr ""
msgid must contains the original english text. The translation goes to msgstr ;)

2022-06-12 08:23 UTC, catdesign-group commented on locales/ru.po
> +msgstr ""
Sorry) I don't have syntax highlighting for .po files. That's why such stupid mistakes. I'll fix it

2022-06-12 08:25 UTC, catdesign-group commented on locales/ru.po
> +msgstr "Оптимизировать PNG"
To translate it correctly, you need to understand. Why is it slow. Maybe you meant optimizing PNG without loss of quality?

2022-06-12 08:27 UTC, catdesign-group commented on locales/ru.po
> +msgstr "Разрешение"
This field is used in the interface where the user sets the image size vertically and horizontally. That is, permission. Therefore, I translated it so that it is clearer for a Russian-speaking user.

2022-06-12 08:30 UTC, catdesign-group commented
Made a commit with changes. Thanks for the help)

2022-06-13 10:40 UTC, flozz commented on locales/ru.po
> +msgstr "Разрешение"
Ok, I just wanted to be sure it is ok in Russian :)

2022-06-13 10:44 UTC, flozz commented on locales/ru.po
> +msgstr "Оптимизировать PNG"
PNG are always optimized losslessly. This checkbox only enable a more "aggressive" preset that can optimize a bit more but that is really really slow to execute.

I may remove this option later as the gain do not worth the additional computation time in my opinion. 

![image](https://user-images.githubusercontent.com/971438/173337057-084eede0-64ab-4fb7-a76b-82fb21d09d89.png)

2022-06-13 10:54 UTC, catdesign-group commented on locales/ru.po
> +msgstr "Оптимизировать PNG"
Thank you, now the meaning is clear. Translated the line

2022-06-13 10:55 UTC, catdesign-group commented on locales/ru.po
> +"Un'interfaccia grafica per convertire e ottimizzare immagini JPEG, PNG e "
I translated it)

2022-06-13 11:00 UTC, catdesign-group commented on locales/ru.po
> +msgstr "Разрешение"
We have a lot of different meanings for the same words. I try to choose the most appropriate ones. And I'm trying to take those words that will be displayed normally in the program interface.

For example , the word output can be translated as:
Выход (the best option)
Вывод (the best option)
Результат
Итог

But everything is complicated by the fact that in combination with other words, the meaning changes a little.

Don't worry. Translation +- high-quality)))

2022-06-13 12:05 UTC, flozz commented
Thank you for your fixes!

Here are some screenshots of the translated UI (some of the GTK stock strings are not translated because I haven't installed GTK Russian translation on my PC).

Please check and if everything looks OK for you, I will merge :D

-----

![Capture d’écran du 2022-06-13 13-56-55](https://user-images.githubusercontent.com/971438/173348826-f8e3bca6-357d-4b9e-86c9-4191d4c88b84.png)
![Capture d’écran du 2022-06-13 13-56-57](https://user-images.githubusercontent.com/971438/173348844-28d81ca8-70e8-4b73-9dc2-e12dfd6f6242.png)

-----

![image](https://user-images.githubusercontent.com/971438/173348949-5e3d8e4f-d81e-4bd9-8fff-f4c3d1af09cf.png)
![Capture d’écran du 2022-06-13 13-58-51](https://user-images.githubusercontent.com/971438/173348978-431baf7d-032a-4b17-91f8-18c4eedf48ef.png)

----

![image](https://user-images.githubusercontent.com/971438/173349072-8c30c94e-d578-46bb-be24-2f620eb29118.png)
![Capture d’écran du 2022-06-13 13-58-02](https://user-images.githubusercontent.com/971438/173349188-994491d9-1c16-41df-be91-5ca92eb0be54.png)
![Capture d’écran du 2022-06-13 13-58-31](https://user-images.githubusercontent.com/971438/173349198-3fcaf43f-bed4-42c7-a77f-89d240c3f5c4.png)

2022-06-13 12:13 UTC, merged

2022-06-13 12:14 UTC, flozz commented
Thank you :)